### PR TITLE
PLAT-8294 : supporting private cluster

### PR DESCRIPTION
**Pull request by ddl-ymaachi**
Adding support for:

- AKS private cluster with user managed identity 
- ACR private registry

### CODE REVIEW

**Comment by ddl-ymaachi** [comment]
example `azure-main.tf` to test the new features: 
```
#########################################################################
########### Create Vnet and Subnet to test Private AKS and ACR ##########
#########################################################################
terraform {
  required_version = ">= 1.3.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.45"
    }

    random = {
      source  = "hashicorp/random"
      version = "~> 3.1"
    }
  }
}

provider "azurerm" {
  partner_id = "31912fbf-f6dd-5176-bffb-0a01e8ac71f2"
  features {}
}

variable "ipspace" {
  description = "CIDR block for AKS and ACR Vnet"
  type        = string
  default     = "172.16.0.0/16"
}

variable "address_prefixes" {
  description = "CIDR block for AKS and ACR Subnet"
  type        = list(string)
  default     = ["172.16.0.0/24"]
}
variable "tags" {
  type    = map(string)
  default = {
    environment = "production"
    department  = "engineering"
    project     = "azure-platform"
  }
}
# Create Vnet for AKS and ACR
resource "azurerm_virtual_network" "aks_vnet" {
  name                = "aks-ymi-private-vnet"
  location            = "westeurope"
  resource_group_name = "ymi-domino"
  address_space       = [var.ipspace]
  tags                = var.tags
}
# Create Subnet for AKS and ACR
resource "azurerm_subnet" "aks_subnet" {
  name                 = "aks-ymi-private-subnet"
  resource_group_name  = "ymi-domino"
  virtual_network_name = azurerm_virtual_network.aks_vnet.name
  address_prefixes     = var.address_prefixes
}
#########################################################################
##################### Domino Infrastructure #############################
#########################################################################
module "domino-aks" {
  source                              = "./terraform-azure-aks-acr"
  api_server_authorized_ip_ranges     = null
  resource_group                      = "ymi-domino"
  deploy_id                           = "ymi-private"
  kubeconfig_output_path              = "./config/config"
  kubernetes_version                  = "1.28"
  aks_subnet_name                     = "aks-ymi-private-subnet" # Required for private cluster or private registry. A pre-existing VNet and Subnet are necessary.
  aks_vnet_name                       = "aks-ymi-private-vnet"   # Required for private cluster or private registry. A pre-existing VNet and Subnet are necessary.
  aks_vnet_rg_name                    = "ymi-domino"             # Required for private cluster or private registry. A pre-existing VNet and Subnet are necessary.
  cni_overlay_enabled                 = true
  private_acr_enabled                 = false
  private_cluster_enabled             = true
  private_cluster_public_fqdn_enabled = false
  namespaces = {
    platform = "domino-platform"
    compute  = "domino-compute"
  }


  node_pools = {
    compute = {
      zones = ["1"]

      # counts are per zone
      initial_count = 3
    }
    gpu = {
      zones = []

      # counts are per zone
      min_count     = 0
      max_count     = 1
      initial_count = 0
    }
    platform = {
      zones = ["1"]

      # counts are per zone
      min_count     = 3
      max_count     = 6
      initial_count = 3
    }
    system = {
      zones = ["1"]

      # counts are per zone
      min_count     = 3
      max_count     = 6
      initial_count = 3
    }
  }
}

output "STORAGE_ACCOUNT_PRIMARY_ACCESS_KEY" {
  value     = module.domino-aks.storage_account.primary_access_key
  sensitive = true
}
output "STORAGE_ACCOUNT_NAME" {
  value = module.domino-aks.storage_account.name
}
output "STORAGE_ACCOUNT_PRIMARY_FILE_ENDPOINT" {
  value = module.domino-aks.storage_account.primary_file_endpoint
}
output "STORAGE_ACCOUNT_PRIMARY_CONNECTION_STRING" {
  value     = module.domino-aks.storage_account.primary_connection_string
  sensitive = true
}
output "STORAGE_ACCOUNT_BACKUPS_CONTAINER_NAME" {
  value = module.domino-aks.containers.backups.name
}
output "STORAGE_ACCOUNT_PROJECTS_CONTAINER_NAME" {
  value = module.domino-aks.containers.projects.name
}
output "CONTAINER_REGISTRY" {
  value = module.domino-aks.domino_acr.login_server
}
output "IMAGE_BUILD_WORKLOAD_IDENTITY" {
  value = true
}
output "IMAGE_BUILD_CLIENT_ID" {
  value = module.domino-aks.workload_identities.hephaestus.client_id
}
```

**Comment by ddl-ymaachi** [comment]
Tests conducted include:
| Tested combinations | AKS     | ACR     |
|---------------------|---------|---------|
| OK                  | Private | Private |
| OK                  | Public  | Public  |
| OK                  | Private | Public  |
| OK                  | Public  | Private |

**Review by ddl-dclegg — APPROVED** [review]

**Comment by ddl-dclegg** [comment]
@yas51ne Looks good generally, but we definitely need to get these tests passing.

**Comment by ddl-ymaachi** [comment]
last execution worked, but it looks like this one failed because the terraform command not found on the ci/cd agent: https://app.circleci.com/pipelines/github/dominodatalab/terraform-azure-aks/408/workflows/63da1d6b-1edd-4c04-918f-82f3ec8e0479/jobs/635

**Review by ddl-dclegg — CHANGES_REQUESTED** [review]
@yas51ne Now that the container tooling is updated, we're getting failures on some outputs. Can you take a look?

Just as an update on _why_ the fixes were needed, @ddl-sacuna found that the `azure-cli` image had a recent breaking change, and thus we needed updates to handle packages properly.

**Comment by ddl-ymaachi** [comment]
@ddl-dclegg I pushed the fix, it should be fine now

**Review by ddl-dclegg — APPROVED** [review]
Thanks @ddl-ymaachi!

**Pull request merged**
