### PR TITLE
remove azure diagnostic retention settings

### PR DESCRIPTION
**Pull request by steved**
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy

### CODE REVIEW

**Comment by steved** [comment]
Upgrade failure is expected.

**Review by fraenkel — APPROVED** [review]
are we sure? it also links up logging.

**Comment by steved** [comment]
> are we sure? it also links up logging.

Err yep, definitely misread the deprecation.

**Comment by steved** [comment]
Confirmed logs are still being ingested and the default retention is the workspace default.

**Pull request merged**
